services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/texts:/app/texts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
