version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/texts:/app/texts
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
